apiVersion: v1
kind: Service
metadata:
  name: rapidfort-project-service
spec:
  selector:
    app: rapidfort-project
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 5000 
  type: LoadBalancer
