name: Build Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t rapidfort-project .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Push Docker image
      run: |
        docker tag rapidfort-project ${{ secrets.DOCKERHUB_USERNAME }}/rapidfort-project:v1.0
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/rapidfort-project:v1.0
